import { NextResponse } from 'next/server';

// Mock data - in production, this would come from a database
const mockTeamMembers = [
  {
    id: '1',
    name: '🌟 智能体世界专家',
    role: '视角转换/未来布局',
    status: 'active',
    completedTasks: 15,
    contributionScore: 245,
    currentTask: '分析市场趋势',
  },
  {
    id: '2',
    name: '📚 咨询师',
    role: '研究分析',
    status: 'active',
    completedTasks: 12,
    contributionScore: 198,
    currentTask: '竞品调研',
  },
  {
    id: '3',
    name: '🏗️ 架构师',
    role: '架构设计',
    status: 'active',
    completedTasks: 18,
    contributionScore: 320,
    currentTask: '系统架构优化',
  },
  {
    id: '4',
    name: '⚡ Executor',
    role: '执行实现',
    status: 'active',
    completedTasks: 22,
    contributionScore: 375,
    currentTask: '开发仪表盘组件',
  },
  {
    id: '5',
    name: '🛡️ 系统管理员',
    role: '运维部署',
    status: 'idle',
    completedTasks: 10,
    contributionScore: 165,
    currentTask: '监控服务器状态',
  },
  {
    id: '6',
    name: '🧪 测试员',
    role: '测试调试',
    status: 'active',
    completedTasks: 14,
    contributionScore: 230,
    currentTask: '编写单元测试',
  },
  {
    id: '7',
    name: '🎨 设计师',
    role: 'UI设计',
    status: 'active',
    completedTasks: 16,
    contributionScore: 280,
    currentTask: '设计数据可视化',
  },
  {
    id: '8',
    name: '📣 推广专员',
    role: '推广SEO',
    status: 'idle',
    completedTasks: 8,
    contributionScore: 135,
    currentTask: '优化SEO关键词',
  },
  {
    id: '9',
    name: '💼 销售客服',
    role: '销售客服',
    status: 'active',
    completedTasks: 11,
    contributionScore: 185,
    currentTask: '客户跟进',
  },
  {
    id: '10',
    name: '💰 财务',
    role: '财务会计',
    status: 'offline',
    completedTasks: 6,
    contributionScore: 98,
    currentTask: '月度报表',
  },
  {
    id: '11',
    name: '📺 媒体',
    role: '媒体宣传',
    status: 'active',
    completedTasks: 9,
    contributionScore: 152,
    currentTask: '内容策划',
  },
];

const mockTasks = [
  {
    id: 't1',
    title: '开发仪表盘组件',
    assignee: '⚡ Executor',
    status: 'in-progress',
    priority: 'high',
    dueDate: '2026-03-07',
  },
  {
    id: 't2',
    title: '设计数据可视化',
    assignee: '🎨 设计师',
    status: 'in-progress',
    priority: 'high',
    dueDate: '2026-03-07',
  },
  {
    id: 't3',
    title: '编写单元测试',
    assignee: '🧪 测试员',
    status: 'todo',
    priority: 'medium',
    dueDate: '2026-03-08',
  },
  {
    id: 't4',
    title: '系统架构优化',
    assignee: '🏗️ 架构师',
    status: 'review',
    priority: 'high',
    dueDate: '2026-03-06',
  },
  {
    id: 't5',
    title: '竞品调研',
    assignee: '📚 咨询师',
    status: 'done',
    priority: 'medium',
    dueDate: '2026-03-05',
  },
  {
    id: 't6',
    title: '部署到生产环境',
    assignee: '🛡️ 系统管理员',
    status: 'todo',
    priority: 'low',
    dueDate: '2026-03-10',
  },
  {
    id: 't7',
    title: 'SEO优化',
    assignee: '📣 推广专员',
    status: 'in-progress',
    priority: 'medium',
    dueDate: '2026-03-09',
  },
  {
    id: 't8',
    title: '客户反馈整理',
    assignee: '💼 销售客服',
    status: 'done',
    priority: 'high',
    dueDate: '2026-03-04',
  },
];

const mockActivities = [
  {
    id: 'a1',
    type: 'commit',
    user: '⚡ Executor',
    message: 'feat: 添加仪表盘组件',
    timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    icon: '📝',
  },
  {
    id: 'a2',
    type: 'pr',
    user: '🏗️ 架构师',
    message: 'PR #42: 系统架构优化',
    timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    icon: '🔀',
  },
  {
    id: 'a3',
    type: 'issue',
    user: '🧪 测试员',
    message: 'Issue #123: 修复测试用例',
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    icon: '🐛',
  },
  {
    id: 'a4',
    type: 'commit',
    user: '🎨 设计师',
    message: 'style: 优化数据可视化样式',
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    icon: '📝',
  },
  {
    id: 'a5',
    type: 'comment',
    user: '🌟 智能体世界专家',
    message: '评审: 架构方案需要调整',
    timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    icon: '💬',
  },
  {
    id: 'a6',
    type: 'issue',
    user: '📚 咨询师',
    message: 'Issue #124: 竞品分析报告',
    timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    icon: '📊',
  },
  {
    id: 'a7',
    type: 'commit',
    user: '🛡️ 系统管理员',
    message: 'chore: 更新部署脚本',
    timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    icon: '📝',
  },
  {
    id: 'a8',
    type: 'pr',
    user: '📣 推广专员',
    message: 'PR #43: SEO优化更新',
    timestamp: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
    icon: '🔀',
  },
];

export async function GET() {
  const stats = {
    totalTasks: mockTasks.length,
    completedTasks: mockTasks.filter((t) => t.status === 'done').length,
    activeMembers: mockTeamMembers.filter((m) => m.status === 'active').length,
    avgResponseTime: '2.5h',
  };

  return NextResponse.json({
    members: mockTeamMembers,
    tasks: mockTasks,
    activities: mockActivities,
    stats,
  });
}
